syntax = "proto3";

package com.gth.auth.v1;

option java_multiple_files = true;
option java_package = "com.gth.auth.v1";
option java_outer_classname = "AuthServiceProto";

service AuthService {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse);
}

message RegisterRequest {
  string email = 1;
  string password = 2;
  string name = 3;
}

message RegisterResponse {
  string userId = 1;
  string access_token = 2;
  string refresh_token = 3;
  string expire_in = 4;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  string userId = 1;
  string name = 2;
  string access_token = 3;
  string refresh_token = 4;
  int64 expire_in = 5;
}

message RefreshTokenRequest {
  string refresh_token = 1;
}

message RefreshTokenResponse {
  string access_token = 1;
  string refresh_token = 2;
  int64 expire_in = 5;
}